{{- if and .Values.proxy.password (not .Values.proxy.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "clamav-rest.fullname" . }}-proxy
  labels:
    {{- include "clamav-rest.labels" . | nindent 4 }}
type: Opaque
data:
  proxy-password: {{ .Values.proxy.password | b64enc | quote }}
{{- end }}
