apiVersion: v1
kind: Service
metadata:
  name: {{ include "clamav-rest.fullname" . }}
  labels:
    {{- include "clamav-rest.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.httpsPort }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "clamav-rest.selectorLabels" . | nindent 4 }}
