apiVersion: v1
entries:
  clamav-rest:
  - apiVersion: v2
    appVersion: latest
    created: "2026-02-25T14:23:05.591168318+01:00"
    description: ClamAV antivirus scanner with REST API
    digest: eada27283e11b40c6f3aa962e86bdbc372610031dbd1e39e115b2c4dce78bfd4
    home: https://github.com/ajilach/clamav-rest
    keywords:
    - clamav
    - antivirus
    - malware
    - scanner
    - rest-api
    maintainers:
    - name: ajilach
    name: clamav-rest
    sources:
    - https://github.com/ajilach/clamav-rest
    type: application
    urls:
    - clamav-rest-0.1.0.tgz
    version: 0.1.0
generated: "2026-02-25T14:23:05.590029144+01:00"
